FROM rust

# PRE-FETCH MANY DEPS
WORKDIR /scratch
COPY owasm /scratch/owasm
COPY go-owasm /scratch/go-owasm
RUN cd go-owasm && cargo fetch
# allow non-root user to download more deps later
RUN chmod -R 777 /usr/local/cargo


## COPY BUILD SCRIPTS

WORKDIR /code
RUN rm -rf /scratch

COPY go-owasm/build/build_linux.sh /opt
RUN chmod +x /opt/build*

RUN mkdir /.cargo
RUN chmod +rx /.cargo
COPY go-owasm/build/cargo-config /.cargo/config

CMD ["/opt/build_linux.sh"]
